{{- if .Values.eventsService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: events-service
spec:
  replicas: {{ .Values.eventsService.replicas }}
  selector:
    matchLabels:
      app: events-service
  template:
    metadata:
      labels:
        app: events-service
    spec:
      containers:
      - name: events-service
        image: "{{ .Values.eventsService.image.repository }}:{{ .Values.eventsService.image.tag }}"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: events-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: events-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
{{- end }}